services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    restart: unless-stopped

  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
    env_file: ./auth-service/.env
    environment:
      - KAFKA_BROKER=kafka:9092
    ports:
      - "4002:4002"
    restart: unless-stopped

  gateway:
    container_name: gateway
    build:
      context: ./gateway
    env_file: ./gateway/.env
    environment:
      - KAFKA_BROKER=kafka:9092
    ports:
      - "4000:4000"
    restart: unless-stopped
    depends_on:
      - auth-service

  posts-service:
    container_name: posts-service
    build:
      context: posts-service
    env_file: posts-service/.env
    environment:
      - KAFKA_BROKER=kafka:9092
    ports:
      - "4001:4001"
    restart: unless-stopped
